### ISSUE TITLE
session 'fetch is not defined' backend

### ISSUE THREAD

**Issue by ghost** [shadeemerhi/imessage-graphql#4]
url: 'http://localhost:3000/api/auth/session',
  message: 'fetch is not defined'

[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error fetch is not define

`context: async ({ req, res }) => {
      const session = await getSession({ req });

      return { session: session as Session };
    }

`

have already set  NEXTAUTH_URL=http://localhost:3000 to my environment variable

**Comment by jzenzinger** [comment]
What node version you have? If its 16.xxx, try to update it to the latest version and rerun backend.

**Comment by ghost** [comment]
thanks jzenzinger....it solved by updatimg my node....
